### ISSUE TITLE
Specifying only one of `freeze_index` or `freeze_headers` if `df_to_sheet()` fails

### ISSUE THREAD

**Issue by vshih** [aiguofer/gspread-pandas#23]
```python
import gspread_pandas as gp
import pandas as pd
df = pd.DataFrame([{'a': 1, 'b': 2}])
spread = gp.client.Spread(...)

# OK
spread.df_to_sheet(df, sheet='Sheet1')
# OK
spread.df_to_sheet(df, sheet='Sheet2', freeze_index=True, freeze_headers=True)

# FAILS
spread.df_to_sheet(df, sheet='Sheet3', freeze_index=True)
# FAILS
spread.df_to_sheet(df, sheet='Sheet4', freeze_headers=True)
```

Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "</Users/vshih/.virtualenvs/salesforce_asset/lib/python3.4/site-packages/decorator.py:decorator-gen-15>", line 2, in df_to_sheet
  File "/Users/vshih/.virtualenvs/salesforce_asset/lib/python3.4/site-packages/gspread_pandas/client.py", line 243, in _ensure_auth
    return func(self, *args, **kwargs)
  File "/Users/vshih/.virtualenvs/salesforce_asset/lib/python3.4/site-packages/gspread_pandas/client.py", line 632, in df_to_sheet
    None if not freeze_index else index_size)
  File "</Users/vshih/.virtualenvs/salesforce_asset/lib/python3.4/site-packages/decorator.py:decorator-gen-16>", line 2, in freeze
  File "/Users/vshih/.virtualenvs/salesforce_asset/lib/python3.4/site-packages/gspread_pandas/client.py", line 243, in _ensure_auth
    return func(self, *args, **kwargs)
  File "/Users/vshih/.virtualenvs/salesforce_asset/lib/python3.4/site-packages/gspread_pandas/client.py", line 675, in freeze
    'requests': create_frozen_request(self.sheet.id, rows, cols)
  File "/Users/vshih/.virtualenvs/salesforce_asset/lib/python3.4/site-packages/gspread_pandas/util.py", line 123, in create_frozen_request
    if rows >= 0:
TypeError: unorderable types: NoneType() >= int()
```

**Comment by aiguofer** [comment]
Hi, thanks for reporting!

I've fixed it and released a new version.
